[package]
name = "bitcore"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib", "staticlib"]

[dependencies]
flutter_rust_bridge = "2.3.0"
serialport = "4.4.0"

[dev-dependencies]
assert_cmd = "2.0.0"
